export const reports = {
	balance: "Balansrapport",
	"balance.description": "Balansrapporten visar företagets tillgångar, eget kapital och skulder vid en viss tidpunkt.",
	"balance.assets": "Tillgångar",
	"balance.assets.fixed": "Anläggningstillgångar",
	"balance.assets.fixed.intangible": "Immateriella tillgångar",
	"balance.assets.fixed.tangible": "Materiella tillgångar",
	"balance.assets.fixed.financial": "Finansiella tillgångar",
	"balance.assets.current": "Omsättningstillgångar",
	"balance.assets.current.inventories": "Varulager",
	"balance.assets.current.receivables": "Kundfordringar",
	"balance.assets.current.prepaid": "Förutbetalda kostnader och upplupna intäkter",
	"balance.assets.current.financial": "Finansiella tillgångar",
	"balance.equity-liabilities": "Eget kapital och skulder",
	"balance.equity-liabilities.equity": "Eget kapital",
	"balance.equity-liabilities.equity.share": "Aktiekapital",
	"balance.equity-liabilities.liabilities": "Skulder",
	"balance.equity-liabilities.liabilities.reserves": "Reserveringar",
	"balance.equity-liabilities.liabilities.provisions": "Avsättningar",
	"balance.equity-liabilities.liabilities.long": "Långfristiga skulder",
	"balance.equity-liabilities.liabilities.short": "Kortfristiga skulder",
	"balance.equity-liabilities.liabilities.tax": "Skatt och moms",
	"balance.equity-liabilities.liabilities.employer": "Arbetsgivaravgifter",
	"balance.equity-liabilities.liabilities.other": "Övriga skulder",
	result: "Resultatrapport",
	"result.description": "Resultatrapporten visar företagets intäkter och kostnader under en viss period.",
	"result.operating": "Rörelseresultat",
	"result.operating.income": "Rörelsens intäkter",
	"result.operating.income.net": "Nettoomsättning",
	"result.operating.income.other": "Övriga rörelseintäkter",
	"result.operating.expenses": "Rörelsens kostnader",
	"result.operating.expenses.cogs": "Varukostnader",
	"result.operating.expenses.premises": "Lokalkostnader",
	"result.operating.expenses.consumables": "Förbrukningsinventarier",
	"result.operating.expenses.selling": "Försäljningskostnader",
	"result.operating.expenses.administration": "Administrationskostnader",
	"result.operating.expenses.personnel": "Personalkostnader",
	"result.operating.expenses.depreciation": "Avskrivningar",
	"result.operating.expenses.other": "Övriga rörelsekostnader",
	"result.financial": "Finansiella poster",
	"result.financial.income": "Finansiella intäkter",
	"result.financial.income.shares": "Utdelningar från aktieinnehav",
	"result.financial.income.associated": "Intäkter från intressebolag",
	"result.financial.income.interest": "Ränteintäkter",
	"result.financial.income.other": "Övriga finansiella intäkter",
	"result.financial.expenses": "Finansiella kostnader",
	"result.financial.expenses.interest": "Räntekostnader",
	"result.financial.expenses.other": "Övriga finansiella kostnader",
	"result.adjustments": "Bokslutsdispositioner",
	"result.adjustments.extraordinary": "Extraordinära poster",
	"result.adjustments.extraordinary.income": "Extraordinära intäkter",
	"result.adjustments.extraordinary.expenses": "Extraordinära kostnader",
	"result.adjustments.appropriations": "Årets bokslutsdispositioner",
	"result.adjustments.appropriations.tax": "Skatt på årets bokslutsdispositioner",
	"result.adjustments.appropriations.group": "Koncernbidrag",
	"result.adjustments.appropriations.reserves": "Överavskrivningar",
	"result.adjustments.appropriations.other": "Övriga bokslutsdispositioner",
	"result.adjustments.final": "Årets resultat",
	"result.adjustments.final.tsaxes": "Skatter",
	"resulto.adjMments.final.profit": "Skatt på årets resultat",
	vat: "Momsdeklaration",
	"vat.description": "Momsrapport för perioden enligt Skatteverkets krav.",
	"vat.A": "Block A - Momspliktig försäljning eller uttag exklusive moms",
	"vat.A.05": "Fält 05 - Momspliktig försäljning som inte ingår i ruta 06, 07 eller 08",
	"vat.A.06": "Fält 06 - Mompliktiga uttag",
	"vat.A.07": "Fält 07 - Beskattningsunderlag vid vinstmarginalbeskattning",
	"vat.A.08": "Fält 08 - Hyresinkomster vid frivillig skattskyldighet",
	"vat.B": "Block B - Momspliktig försäljning eller uttag exklusive moms",
	"vat.B.10": "Fält 10 - Utgående moms 25%",
	"vat.B.11": "Fält 11 - Utgående moms 12%",
	"vat.B.12": "Fält 12 - Utgående moms 6%",
	"vat.C": "Momspliktiga inköp vid omvänd betalningsskyldighet",
	"vat.C.20": "Fält 20 - Inköp av varor från annat EU-land",
	"vat.C.21": "Fält 21 - Inköp av tjänster från ett annat EU-land, enligt huvudregeln",
	"vat.C.22": "Fält 22 - Inköp av tjänster från länder utanför EU",
	"vat.C.23": "Fält 23 - Inköp av varor i Sverige som köparen är betalningsskyldig för",
	"vat.C.24": "Fält 24 - Övriga inköp av tjänster i Sverige som köparen är betalningsskyldig för",
	"vat.D": "Block D - Utgående moms på inköp i fält 20-24",
	"vat.D.30": "Fält 30 - Utgående moms 25 %",
	"vat.D.31": "Fält 31 - Utgående moms 12 %",
	"vat.D.32": "Fält 32 - Utgående moms 6 %",
	"vat.E": "Block E - Försäljning med mera som är undantagen från moms",
	"vat.E.35": "Fält 35 - Försäljning av varor till ett annat EU-land",
	"vat.E.36": "Fält 36 - Försäljning av varor utanför EU",
	"vat.E.37": "Fält 37 - Mellanmans inköp av varor vid trepartshandel",
	"vat.E.38": "Fält 38 - Mellanmans försäljning av varor vid trepartshandel",
	"vat.E.39": "Fält 39 - Försäljning av tjänster till näringsidkare i annat EU-land enligt huvudregeln",
	"vat.E.40": "Fält 40 - Övriga försäljning av av tjänster omsatta utanför Sverige",
	"vat.E.41": "Fält 41 - Försäljning när köparen är skatteskyldig i Sverige",
	"vat.E.42": "Fält 42 - Övrig försäljning med mera",
	"vat.F": "Block F - Ingående moms",
	"vat.F.48": "Fält 48 - Ingående moms att dra av",
	"vat.G": "Block G - Moms att betala eller få tillbaka",
	"vat.G.49": "Fält 49 - Moms att betala eller få tillbaka",
	"vat.H": "Block H - moms vid import",
	"vat.H.50": "Fält 50 -Beskattningsunderlag vid import",
	"vat.I": "Block I - Utgående moms på import i fält 50",
	"vat.I.60": "Fält 60 - Utgående moms 25%",
	"vat.I.61": "Fält 61 - Utgående moms 12%",
	"vat.I.62": "Fält 62 - Utgående moms 6%",
}
