export const reports = {
	balance: "Balansrapport",
	"balance.description": "Balansrapporten visar företagets tillgångar, eget kapital och skulder vid en viss tidpunkt.",
	"balance.assets": "Tillgångar",
	"balance.assets.fixed": "Anläggningstillgångar",
	"balance.assets.fixed.intangible": "Immateriella tillgångar",
	"balance.assets.fixed.tangible": "Materiella tillgångar",
	"balance.assets.fixed.financial": "Finansiella tillgångar",
	"balance.assets.current": "Omsättningstillgångar",
	"balance.assets.current.inventories": "Varulager",
	"balance.assets.current.receivables": "Kundfordringar",
	"balance.assets.current.prepaid": "Förutbetalda kostnader och upplupna intäkter",
	"balance.assets.current.financial": "Finansiella tillgångar",
	"balance.equity-liabilities": "Eget kapital och skulder",
	"balance.equity-liabilities.equity": "Eget kapital",
	"balance.equity-liabilities.equity.share": "Aktiekapital",
	"balance.equity-liabilities.liabilities": "Skulder",
	"balance.equity-liabilities.liabilities.reserves": "Reserveringar",
	"balance.equity-liabilities.liabilities.provisions": "Avsättningar",
	"balance.equity-liabilities.liabilities.long": "Långfristiga skulder",
	"balance.equity-liabilities.liabilities.short": "Kortfristiga skulder",
	"balance.equity-liabilities.liabilities.tax": "Skatt och moms",
	"balance.equity-liabilities.liabilities.employer": "Arbetsgivaravgifter",
	"balance.equity-liabilities.liabilities.other": "Övriga skulder",
	result: "Resultatrapport",
	"result.description": "Resultatrapporten visar företagets intäkter och kostnader under en viss period.",
	"result.operating": "Rörelseresultat",
	"result.operating.income": "Rörelsens intäkter",
	"result.operating.income.net": "Nettoomsättning",
	"result.operating.income.other": "Övriga rörelseintäkter",
	"result.operating.expenses": "Rörelsens kostnader",
	"result.operating.expenses.cogs": "Varukostnader",
	"result.operating.expenses.premises": "Lokalkostnader",
	"result.operating.expenses.consumables": "Förbrukningsinventarier",
	"result.operating.expenses.selling": "Försäljningskostnader",
	"result.operating.expenses.administration": "Administrationskostnader",
	"result.operating.expenses.personnel": "Personalkostnader",
	"result.operating.expenses.depreciation": "Avskrivningar",
	"result.operating.expenses.other": "Övriga rörelsekostnader",
	"result.financial": "Finansiella poster",
	"result.financial.income": "Finansiella intäkter",
	"result.financial.income.shares": "Utdelningar från aktieinnehav",
	"result.financial.income.associated": "Intäkter från intressebolag",
	"result.financial.income.interest": "Ränteintäkter",
	"result.financial.income.other": "Övriga finansiella intäkter",
	"result.financial.expenses": "Finansiella kostnader",
	"result.financial.expenses.interest": "Räntekostnader",
	"result.financial.expenses.other": "Övriga finansiella kostnader",
	"result.adjustments": "Bokslutsdispositioner",
	"result.adjustments.extraordinary": "Extraordinära poster",
	"result.adjustments.extraordinary.income": "Extraordinära intäkter",
	"result.adjustments.extraordinary.expenses": "Extraordinära kostnader",
	"result.adjustments.appropriations": "Årets bokslutsdispositioner",
	"result.adjustments.appropriations.tax": "Skatt på årets bokslutsdispositioner",
	"result.adjustments.appropriations.group": "Koncernbidrag",
	"result.adjustments.appropriations.reserves": "Överavskrivningar",
	"result.adjustments.appropriations.other": "Övriga bokslutsdispositioner",
	"result.adjustments.final": "Årets resultat",
	"result.adjustments.final.tsaxes": "Skatter",
	"resulto.adjMments.final.profit": "Skatt på årets resultat",
	vat: "Moms",
	"vat.description": "Momsrapport för perioden enligt Skatteverkets krav.",
	"vat.A05": "Fält A05",
	"vat.A06": "Fält A06",
	"vat.A07": "Fält A07",
	"vat.A08": "Fält A08",
	"vat.B10": "Fält B10",
	"vat.B11": "Fält B11",
	"vat.B12": "Fält B12",
	"vat.C20": "Fält C20",
	"vat.C21": "Fält C21",
	"vat.C22": "Fält C22",
	"vat.C23": "Fält C23",
	"vat.C24": "Fält C24",
	"vat.D30": "Fält D30",
	"vat.D31": "Fält D31",
	"vat.D32": "Fält D32",
	"vat.E35": "Fält E35",
	"vat.E36": "Fält E36",
	"vat.E37": "Fält E37",
	"vat.E38": "Fält E38",
	"vat.E39": "Fält E39",
	"vat.E40": "Fält E40",
	"vat.E41": "Fält E41",
	"vat.E42": "Fält E42",
	"vat.F48": "Fält F48",
	"vat.H50": "Fält H50",
	"vat.I60": "Fält I60",
	"vat.I61": "Fält I61",
	"vat.I62": "Fält I62",
}
