export const reports = {
	balance: "Balance Report",
	"balance.description": "Shows assets, liabilities, and equity.",
	"balance.assets": "Assets",
	"balance.assets.fixed": "Fixed Assets",
	"balance.assets.fixed.intangible": "Intangible Assets",
	"balance.assets.fixed.tangible": "Tangible Assets",
	"balance.assets.fixed.financial": "Financial Assets",
	"balance.assets.current": "Current Assets",
	"balance.assets.current.inventories": "Inventories",
	"balance.assets.current.receivables": "Accounts Receivable",
	"balance.assets.current.prepaid": "Prepaid Expenses and Accrued Income",
	"balance.assets.current.financial": "Financial Assets",
	"balance.equity-liabilities": "Equity and Liabilities",
	"balance.equity-liabilities.equity": "Equity",
	"balance.equity-liabilities.equity.share": "Share Capital",
	"balance.equity-liabilities.liabilities": "Liabilities",
	"balance.equity-liabilities.liabilities.reserves": "Reserves",
	"balance.equity-liabilities.liabilities.provisions": "Provisions",
	"balance.equity-liabilities.liabilities.long": "Long-Term Liabilities",
	"balance.equity-liabilities.liabilities.short": "Short-Term Liabilities",
	"balance.equity-liabilities.liabilities.tax": "Taxes and VAT",
	"balance.equity-liabilities.liabilities.employer": "Employer Contributions",
	"balance.equity-liabilities.liabilities.other": "Other Liabilities",
	result: "Income Statement",
	"result.description": "Shows income and expenses for the period.",
	"result.operating": "Operating Result",
	"result.operating.income": "Operating Income",
	"result.operating.income.net": "Net Revenue",
	"result.operating.income.other": "Other Operating Income",
	"result.operating.expenses": "Operating Expenses",
	"result.operating.expenses.cogs": "Cost of Goods Sold",
	"result.operating.expenses.premises": "Premises Costs",
	"result.operating.expenses.consumables": "Consumables",
	"result.operating.expenses.selling": "Selling Expenses",
	"result.operating.expenses.administration": "Administrative Expenses",
	"result.operating.expenses.personnel": "Personnel Costs",
	"result.operating.expenses.depreciation": "Depreciation",
	"result.operating.expenses.other": "Other Operating Expenses",
	"result.financial": "Financial Items",
	"result.financial.income": "Financial Income",
	"result.financial.income.shares": "Dividends from Shareholdings",
	"result.financial.income.associated": "Income from Associated Companies",
	"result.financial.income.interest": "Interest Income",
	"result.financial.income.other": "Other Financial Income",
	"result.financial.expenses": "Financial Expenses",
	"result.financial.expenses.interest": "Interest Expenses",
	"result.financial.expenses.other": "Other Financial Expenses",
	"result.adjustments": "Year-End Adjustments",
	"result.adjustments.extraordinary": "Extraordinary Items",
	"result.adjustments.extraordinary.income": "Extraordinary Income",
	"result.adjustments.extraordinary.expenses": "Extraordinary Expenses",
	"result.adjustments.appropriations": "Year's Appropriations",
	"result.adjustments.appropriations.tax": "Tax on Year's Appropriations",
	"result.adjustments.appropriations.group": "Group Contributions",
	"result.adjustments.appropriations.reserves": "Excess Depreciation",
	"result.adjustments.appropriations.other": "Other Appropriations",
	"result.adjustments.final": "Year's Result",
	"result.adjustments.final.taxes": "Taxes",
	"result.adjustments.final.profit": "Tax on Year's Result",
	vat: "VAT Report",
	"vat.description": "The period's VAT report as requested by the Swedish Tax Authority.",
	"vat.A": "Block A - Taxable sales or withdrawals excluding VAT",
	"vat.A.05": "Field 05 - Taxable sales not included in fields 06, 07, or 08",
	"vat.A.06": "Field 06 - Taxable withdrawals",
	"vat.A.07": "Field 07 - Tax base for margin taxation",
	"vat.A.08": "Field 08 - Rental income under voluntary tax liability",
	"vat.B": "Block B - Taxable sales or withdrawals excluding VAT",
	"vat.B.10": "Field 10 - Output VAT 25%",
	"vat.B.11": "Field 11 - Output VAT 12%",
	"vat.B.12": "Field 12 - Output VAT 6%",
	"vat.C": "Taxable purchases under reverse charge",
	"vat.C.20": "Field 20 - Purchases of goods from another EU country",
	"vat.C.21": "Field 21 - Purchases of services from another EU country, under the main rule",
	"vat.C.22": "Field 22 - Purchases of services from countries outside the EU",
	"vat.C.23": "Field 23 - Purchases of goods in Sweden where the buyer is liable for VAT",
	"vat.C.24": "Field 24 - Other purchases of services in Sweden where the buyer is liable for VAT",
	"vat.D": "Block D - Output VAT on purchases in fields 20-24",
	"vat.D.30": "Field 30 - Output VAT 25%",
	"vat.D.31": "Field 31 - Output VAT 12%",
	"vat.D.32": "Field 32 - Output VAT 6%",
	"vat.E": "Block E - Sales and other transactions exempt from VAT",
	"vat.E.35": "Field 35 - Sales of goods to another EU country",
	"vat.E.36": "Field 36 - Sales of goods outside the EU",
	"vat.E.37": "Field 37 - Intermediary's purchase of goods in triangular trade",
	"vat.E.38": "Field 38 - Intermediary's sale of goods in triangular trade",
	"vat.E.39": "Field 39 - Sales of services to businesses in another EU country under the main rule",
	"vat.E.40": "Field 40 - Other sales of services supplied outside Sweden",
	"vat.E.41": "Field 41 - Sales where the buyer is liable for VAT in Sweden",
	"vat.E.42": "Field 42 - Other sales and transactions",
	"vat.F": "Input VAT",
	"vat.F.48": "Field 48 - Input VAT to deduct",
	"vat.G": "Block G - VAT to pay or reclaim",
	"vat.G.49": "Field 49 - VAT to pay or reclaim",
	"vat.H": "Block H - VAT on imports",
	"vat.H.50": "Tax base on imports",
	"vat.I": "Block I - Output VAT on imports in field 50",
	"vat.I.60": "Output VAT 25%",
	"vat.I.61": "Output VAT 12%",
	"vat.I.62": "Output VAT 6%",
}
