export const reports = {
	balance: "Balance Report",
	"balance.description": "Shows assets, liabilities, and equity.",
	"balance.assets": "Assets",
	"balance.assets.fixed": "Fixed Assets",
	"balance.assets.fixed.intangible": "Intangible Assets",
	"balance.assets.fixed.tangible": "Tangible Assets",
	"balance.assets.fixed.financial": "Financial Assets",
	"balance.assets.current": "Current Assets",
	"balance.assets.current.inventories": "Inventories",
	"balance.assets.current.receivables": "Accounts Receivable",
	"balance.assets.current.prepaid": "Prepaid Expenses and Accrued Income",
	"balance.assets.current.financial": "Financial Assets",
	"balance.equity-liabilities": "Equity and Liabilities",
	"balance.equity-liabilities.equity": "Equity",
	"balance.equity-liabilities.equity.share": "Share Capital",
	"balance.equity-liabilities.liabilities": "Liabilities",
	"balance.equity-liabilities.liabilities.reserves": "Reserves",
	"balance.equity-liabilities.liabilities.provisions": "Provisions",
	"balance.equity-liabilities.liabilities.long": "Long-Term Liabilities",
	"balance.equity-liabilities.liabilities.short": "Short-Term Liabilities",
	"balance.equity-liabilities.liabilities.tax": "Taxes and VAT",
	"balance.equity-liabilities.liabilities.employer": "Employer Contributions",
	"balance.equity-liabilities.liabilities.other": "Other Liabilities",
	result: "Income Statement",
	"result.description": "Shows income and expenses for the period.",
	"result.operating": "Operating Result",
	"result.operating.income": "Operating Income",
	"result.operating.income.net": "Net Revenue",
	"result.operating.income.other": "Other Operating Income",
	"result.operating.expenses": "Operating Expenses",
	"result.operating.expenses.cogs": "Cost of Goods Sold",
	"result.operating.expenses.premises": "Premises Costs",
	"result.operating.expenses.consumables": "Consumables",
	"result.operating.expenses.selling": "Selling Expenses",
	"result.operating.expenses.administration": "Administrative Expenses",
	"result.operating.expenses.personnel": "Personnel Costs",
	"result.operating.expenses.depreciation": "Depreciation",
	"result.operating.expenses.other": "Other Operating Expenses",
	"result.financial": "Financial Items",
	"result.financial.income": "Financial Income",
	"result.financial.income.shares": "Dividends from Shareholdings",
	"result.financial.income.associated": "Income from Associated Companies",
	"result.financial.income.interest": "Interest Income",
	"result.financial.income.other": "Other Financial Income",
	"result.financial.expenses": "Financial Expenses",
	"result.financial.expenses.interest": "Interest Expenses",
	"result.financial.expenses.other": "Other Financial Expenses",
	"result.adjustments": "Year-End Adjustments",
	"result.adjustments.extraordinary": "Extraordinary Items",
	"result.adjustments.extraordinary.income": "Extraordinary Income",
	"result.adjustments.extraordinary.expenses": "Extraordinary Expenses",
	"result.adjustments.appropriations": "Year's Appropriations",
	"result.adjustments.appropriations.tax": "Tax on Year's Appropriations",
	"result.adjustments.appropriations.group": "Group Contributions",
	"result.adjustments.appropriations.reserves": "Excess Depreciation",
	"result.adjustments.appropriations.other": "Other Appropriations",
	"result.adjustments.final": "Year's Result",
	"result.adjustments.final.taxes": "Taxes",
	"result.adjustments.final.profit": "Tax on Year's Result",
	vat: "VAT Report",
	"vat.description": "The periods VAT report as requested by the Swedish Tax Authority.",
	"vat.A05": "Field A05",
	"vat.A06": "Field A06",
	"vat.A07": "Field A07",
	"vat.A08": "Field A08",
	"vat.B10": "Field B10",
	"vat.B11": "Field B11",
	"vat.B12": "Field B12",
	"vat.C20": "Field C20",
	"vat.C21": "Field C21",
	"vat.C22": "Field C22",
	"vat.C23": "Field C23",
	"vat.C24": "Field C24",
	"vat.D30": "Field D30",
	"vat.D31": "Field D31",
	"vat.D32": "Field D32",
	"vat.E35": "Field E35",
	"vat.E36": "Field E36",
	"vat.E37": "Field E37",
	"vat.E38": "Field E38",
	"vat.E39": "Field E39",
	"vat.E40": "Field E40",
	"vat.E41": "Field E41",
	"vat.E42": "Field E42",
	"vat.F48": "Field F48",
	"vat.H50": "Field H50",
	"vat.I60": "Field I60",
	"vat.I61": "Field I61",
	"vat.I62": "Field I62",
}
